kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-pg
  namespace: client1
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi