apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckan-pg
  namespace: client1
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  local:
    type: localVolumeSource
    path: /mnt/disks/ckan-pg