apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-provisioner
  namespace: kube-system
data:
  file.system.id: {{EFS_ID}}
  aws.region: {{AWS_REGION}}
  provisioner.name: k8s.datashades.links.com.au/aws-efs