kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: ckan-solr
  namespace: client1
spec:
  selector:
    matchLabels:
      app: ckan
      component: solr
  replicas: 1
  template:
    metadata:
      labels:
        app: ckan
        component: solr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      containers:
      - name: ckan-solr
        image: "860798832671.dkr.ecr.ap-southeast-2.amazonaws.com/ckan-solr:base"
        imagePullPolicy: Always
        ports:
        - containerPort: 8983
        resources:
          requests:
            memory: "512M"
            cpu: "100m"