kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: nfs-server
  namespace: client1
spec:
  selector:
      matchLabels:
        app: nfs
        component: server
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs
        component: server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In
                values:
                - nodes
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-export
        resources:
          requests:
            memory: "64M"
            cpu: "100m"
      volumes:
        - name: nfs-export
          persistentVolumeClaim:
            claimName: nfs-ebs