kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-ebs
  namespace: client1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: aws-ebs