kind: Service
apiVersion: v1
metadata:
  name: nfs-service
  namespace: client1
spec:
  ports:
    - port: 2049
      name: nfs
    - port: 20048
      name: mountd
    - port: 111
      name: rpcbind
  selector:
    app: nfs
    component: server