kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ckan-client-efs
  namespace: client1
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi