kind: Service
apiVersion: v1
metadata:
  name: ckan-redis
  namespace: client1
spec:
  ports:
    - port: 6379
      name: redis
      protocol: TCP
  clusterIP: "None"
  selector:
    app: ckan
    component: redis